
all:

	gcc -I/home/mare/Ehsan_lab/Ehsan_Mtk_root/Mtk-1.4.5/include -I/home/mare/Ehsan_lab/Ehsan_Mtk_root/hdfeoslibs/include -L/home/mare/Ehsan_lab/Ehsan_Mtk_root/Mtk-1.4.5/lib -o TOA_Ehsan TOA.c -lMisrToolkit  -lm -lfftw3	
	
clean:

	rm TOA_Ehsan
